# Test build the MoveIt! tutorials. Author: Dave Coleman
sudo: required
dist: trusty
language: generic
python:
  - "2.7"
compiler:
  - gcc
before_install: # Use this to prepare the system to install prerequisites or dependencies
  # Define some config vars
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"
  - sudo -E sh -c 'echo "deb http://packages.ros.org/ros/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python-rosdep python-wstool python-catkin-tools
  # Setup rosdep
  - sudo rosdep init
  - rosdep update

install:
  - sudo apt-get update
  # Install newer version of ruby
  - sudo apt-get -qq install software-properties-common
  - sudo apt-add-repository -y ppa:brightbox/ruby-ng
  - sudo apt-get update
  - sudo apt-get -qq install ruby2.2-dev ruby2.2
  # Install htmlpoofer
  - sudo gem update
  - sudo gem install pkg-config
  - sudo gem install mini_portile2
  - sudo gem install html-proofer
  # Install ROS's version of sphinx
  - sudo apt-get -qq install ros-indigo-rosdoc-lite
  - source /opt/ros/indigo/setup.bash

script:
  # Test build with non-ROS wrapped Sphinx command to allow warnings and errors to be caught
  - sphinx-build -W -b html . native_build
  # Test build with ROS-version of Sphinx command so that it is generated same as ros.org
  - rosdoc_lite -o build .
  # Run HTML tests on generated build output to check for 404 errors, etc
  - htmlproofer ./build --only-4xx --check-html --file-ignore ./build/html/genindex.html,./build/html/search.html,./build/html/index-msg.html --alt-ignore '/.*/' --url-ignore '#'